### ISSUE TITLE
Hyper-V: Tunneling via "vEthernet (external)" workflow is broken

### ISSUE THREAD

**Issue by sairamvg** [openvswitch/ovs-issues#124]
On Windows Hyper-V, when we create the virtual switch "external" and add a NIC (Ethernet 1) to it, Windows creates a virtual adapter - "vEthernet (external)". The IP address and other properties are configured on "vEthernet (external)" instead of "Ethernet 1".
Hyper-V Switch name is "external" and OVS is enabled on it. The external network uses the adapter:  "Ethernet 1"
ovs-vsctl add-br br-pif
ovs-vsctl add-port br-pif "Ethernet 1"
ovs-vsctl add-port br-pif "vEthernet (external)"

ovs-vsctl: Error detected while setting up 'vEthernet (external)': could not add network device vEthernet (NSX-Switch) to ofproto (Invalid argument).  See ovs-vswitchd log for details.

While we can add "external" (switch name) directly, it messes up the Hyper-V Switch Manager UI. It no longer lets you select a different Ethernet Adapter. Deleting the port also ends up deleting the virtual adapter "(vEthernet (external)" from the Network Adapter list.

There seems to be a mismatch in the documentation w.r.t to how "vEthernet (external)" is created: http://docs.openvswitch.org/en/latest/intro/install/windows/

**Comment by Anandkumar26** [comment]
The issue seems to occur with the patch "datapath-windows: Add multiple switch internal ports" commit #cd30b3460ac53719a6b8aaaba89b29c0304ac335

**Comment by aserdean** [comment]
The command:
ovs-vsctl add-port br-pif "vEthernet (external)" is wrong since it is an internal port.
the right form would be:
ovs-vsctl add-port br-pif "vEthernet (external)" -- set Interface "vEthernet (external)" type=internal
The above is needed from 2.6 since the userspace validates what type of port we transmit from the kernel.

As per documentation: 
"Internal ports are the virtual adapters created on the Hyper-V switch using the ovs-vsctl add-br <bridge> command. By default they are created under the following rule "name of bridge" and the adapters are disabled. One needs to enable them and set the corresponding values to it to make them IP-able."

I will send out a patch to remove the obsolete lines from documentation.

I would recommend that you set the IP on the the bridge and add the external port under the bridge.
The behaviour is intended to conform to the OVS bridges.
It also removes the necessity for an extra port.

Regarding the "vEthernet (*)" story. I wanted to create a way to differentiate between interfaces created via OVS and Windows, thus trying to add a port which has host interface name different from the vmport in hyper-v is ignored, using the host name. As you pointed if you add only port vmport name i.e. `external` it will work but I do not recommend it. Deleting the port will also remove from the host. This is intended since you added the port and after removed it.

The Hyper-V manager will not work because of the following reason:
![untitled](https://cloud.githubusercontent.com/assets/5985012/22614343/79fbbd66-ea89-11e6-82eb-6d3f0db09bc2.png)

You will have multiple management interfaces because they are created when adding bridges.
Changing the adapter can be achieved via powershell:
https://technet.microsoft.com/en-us/library/hh848515.aspx

**Comment by Anandkumar26** [comment]
Here external refers to Hyper-v switch name.
The virtual internal network adapter  "vEthernet (external)" is no longer valid in ovs kernel datapath, since it is stored as external. So, Adding vEthernet (external) to the kernel datapath using the command does not work, 
`ovs-vsctl add-port br-pif "vEthernet (external)" -- set Interface "vEthernet (external)" type=internal` 

Also, need to update the documentation on how to change the Hyper-V switch external adapters using power shell commands.

**Comment by aserdean** [comment]
This has been addressed for some time now by: https://github.com/openvswitch/ovs/commit/a0c03adff6c23da64797ce087747f89f56cf2585
