### ISSUE TITLE
Locks are being held for long portions of code

### ISSUE THREAD

**Issue by Samuel-Ghinet** [openvswitch/ovs-issues#19]
When we are in the ingress part of the code (i.e. a packet is arriving and must be processed), we are at IRQL=DPC. At this IRQL, we must process the request (packet incoming) as fast as possible, and we should only allow spin locks and read write locks to be held for small portions of code - because they block the whole CPU.

In the current implementations, the switch context's dispatch lock and the datapath rw lock are held for the entire time a packet is being processed. What makes it even worse is that any IOCTL request that uses these locks will be blocking the CPU for even a longer period of time - this will make the current packet processing stall until the IOCTL unlocks the locks.

The problem gets more important the more CPUs the hypervisor uses.

**Comment by nithinrajub** [comment]
Samuel,
What is the issue you see with a read/write lock? There can be multiple readers. As long as the writer can wait (fairly), this should be fine. Writes should not be that frequent - port addition/deletion or flow creation/deletion.

**Comment by EitanEliahu** [comment]
It would be nice if we can reduce the code which executes in an elevated IRQL. I think there some sections of code which could be removed from the locked section.

**Comment by Samuel-Ghinet** [comment]
Eitan,

I've got a better solution for this IRQL problem. I will soon try to send on the ML something that would help on that part.

**Comment by Samuel-Ghinet** [comment]
A proper way to improve this would be to use reference counting.

**Comment by svinturis** [comment]
This issue was addressed in several patches:
- [adding a reference count to prevent premature deallocation of the global switch context structure;](https://github.com/openvswitch/ovs/commit/6c4e7adb0807155b603eef30a7929c42667bfa38)
- [removing spinlock protection for the global switch context structure.](https://github.com/openvswitch/ovs/commit/3ed424e5e5d614e08a58ffe700bbe88ed0514a7b)

Due to the above I am considering this issue solved and thus closing it.
