### ISSUE TITLE
Could not find DPDK library in default search path

### ISSUE THREAD

**Issue by aduncmj** [openvswitch/ovs-issues#207]
hi,

when I installed OVS with DPDK, I encountered an error after running "./configure --with-dpdk=$DPDK_BUILD" on the command line, detailed errors are listed below,

> configure: error: Could not find DPDK library in default search path, update PKG_CONFIG_PATH for pkg-config to find the .pc file in non-standard location

can anyone help me to solve this problem?

**Comment by igsilya** [comment]
Hi.  DPDK 20.11+ only supports build with meson, and because of that, it's no longer possible to specify a DPDK build directory for OVS.  You need to configure `pkg-config` instead.  Starting with OVS 2.15, option `--with-dpdk` accepts only 3 values: `static`, `shared` or `yes` (which is equal to `static`).  Please, follow instructions in the installation guide: https://docs.openvswitch.org/en/latest/intro/install/dpdk/ .

I think, `./configure` script should give a better error message, though.  We can work on that.

**Comment by aduncmj** [comment]
> Hi. DPDK 20.11+ only supports build with meson, and because of that, it's no longer possible to specify a DPDK build directory for OVS. You need to configure `pkg-config` instead. Starting with OVS 2.15, option `--with-dpdk` accepts only 3 values: `static`, `shared` or `yes` (which is equal to `static`). Please, follow instructions in the installation guide: https://docs.openvswitch.org/en/latest/intro/install/dpdk/ .
> 
> I think, `./configure` script should give a better error message, though. We can work on that.

It works with running `./configure --with-dpdk=static` according to your instruction. Thanks so much!

**Comment by singchia** [comment]
solved by export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig

**Comment by kouamdo** [comment]
> solved by export PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig

with which version of dpdk and ovs ?
