### ISSUE TITLE
LLDP - ovs crash 

### ISSUE THREAD

**Issue by rllf** [openvswitch/ovs-issues#223]
Dear all, I have a ovs problem in context with LLDP and DPDK. ovs crashes when I receive a LLDP message. I think it is related to the "source" value visible in the second picture which is set to source=DPBUF_MALLOC. I have a different setup without problems and in this setup the value is set to  source=DPBUF_STUB. Any idea? 

![image](https://user-images.githubusercontent.com/30687654/129708537-fe60128b-888b-4142-88ee-3a6e36a86b68.png)

![image](https://user-images.githubusercontent.com/30687654/129708186-bf32c548-4220-4327-bbfb-40c4cbd387ee.png)

**Comment by igsilya** [comment]
It looks like you have a coredump.  Could you, please, provide a stack trace?  It's hard to guess what happened otherwise.

**Comment by rllf** [comment]
does this help ? 

![image](https://user-images.githubusercontent.com/30687654/129712102-169dc84c-1ee5-4c80-b9ea-d61400f81324.png)

**Comment by igsilya** [comment]
Not really, too many things are compiled out, unfortunately.  Another thing is that your `info locals` suggests that `dp_packet` structure has fields that it should not have if OVS built with DPDK.  Fields like `base_` and `allocated_` should not be there, `mbuf` should be there instead.  But you said that the problem is with DPDK.  Something is not right here.  Either OVS built without DPDK or the debuginfo is from a completely different build and all the information printed by gdb makes no sense.

**Comment by rllf** [comment]
thx!  in a reference system (ovs & DPDK) I don't see this issue and my GDB looks like this - your hint refers to "packet = { mbuf"
 
![image](https://user-images.githubusercontent.com/30687654/129718867-0c00d495-1ae1-4692-954c-e696e663d157.png)

**Comment by rllf** [comment]
additional, the ovs is build from https://salsa.debian.org/openstack-team/third-party/openvswitch/-/tree/debian/2.15.0+ds1-3 and the debug package should fit but I will double check that.

**Comment by fmoessbauer** [comment]
Hi @igsilya, thanks for the hint regarding the ABI.

This is actually a packaging issue of debian (mixing ovs internal libraries from different builds via update-alternatives).
I just created a bugreport at the project and provided a fix here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=992406

IMO this issue can be closed here as this is not an OVS issue.

Best regards, Felix
