### ISSUE TITLE
Failed to build Module -> geneve_dev_create_fb not defined

### ISSUE THREAD

**Issue by ipseokri** [openvswitch/ovs-issues#251]
Building modules, stage 2.
  MODPOST 6 modules
ERROR: "geneve_dev_create_fb" [/home/odroid/Downloads/ovs/datapath/linux/vport-geneve.ko] undefined!
==================================================================================

I'm tyring to compile on odroid xu4 with kernel version 5.4.167+ and ovs version 2.15.4.

But When I build the kernel module in ordroid, there is an error about undefined Error.

I'm trying to compile this for three weeks.

please give any idea solving this problem.

**Comment by siot-armin-ghani** [comment]
Hi. I'm having the same issue. Is there any updates or workaround regarding this issue? Thanks

**Comment by igsilya** [comment]
The kernel module from OVS source tree is deprecated since OVS 2.15 and doesn't receive updates for support of new kernels, including new stable versions of kernels and kernels provided by distributions, since these can be significantly modified.

The kernel module shipped with 5.4 kernel should be modern enough to use, so you should not need to build the module from OVS sources.

BTW, OVS 2.15 reached end of support quite some time back, the oldest supported version is OVS 2.17.

**Comment by ipseokri** [comment]
> Hi. I'm having the same issue. Is there any updates or workaround regarding this issue? Thanks

I don't remember exactly, but as far as I can remember, it was due to the influence of ovs installed on existing Linux. So, if you build with all the preinstalled kernel modules removed, it will work out.

**Comment by ipseokri** [comment]
> Hi. I'm having the same issue. Is there any updates or workaround regarding this issue? Thanks

```
$ config_file="/etc/depmod.d/openvswitch.conf"
$ for module in datapath/linux/*.ko; do modname="$(basename ${module})"; echo "override ${modname%.ko} * extra" >> "$config_file"; echo "override ${modname%.ko} * weak-updates" >> "$config_file"; done
$ depmod –a
$ /sbin/modprobe openvswitch
$ make modules_install

```

You have to try this. It will work with you! 🙂
