### ISSUE TITLE
Close devices while user-mode applications still have them opened

### ISSUE THREAD

**Issue by aserdean** [openvswitch/ovs-issues#27]
Short description:
You have an environment set and ovs-vswitchd is running and you issue an uninstall. The driver will be uninstalled but a reboot is required to delete the devices (because ovs-vswitchd was running).

We need to close all active connections to the devices before trying to delete them.

**Comment by EitanEliahu** [comment]
Alin,
We plan to have the two processes vswitchd and ovsdb running as services. An uninstaller would stop these services so the open handle to the device would be closed and the driver will unload.
Do you think this would be something that would work for customers?

**Comment by Samuel-Ghinet** [comment]
Well, there would be the case where the customer decides to upgrade the project to a newer version. In this case we'll need to make sure that uninstalling, and then re-installing, will not cause any problem. 

Here the problem would be if the devices would still be existing after ovs-vswitch was killed, and the new version ovs kernel would try creating a new device.

I haven't tested this scenario, but we'll need to make sure that it behaves correctly.

**Comment by EitanEliahu** [comment]
Sam, if all open handles to device are closed and then the driver is unloaded, where do you see the problem?

**Comment by Samuel-Ghinet** [comment]
Oh yes, killing the vswitchd actually closes all its handles automatically.

**Comment by aserdean** [comment]
Let us suppose that somebody will unload the driver before the service/binary is stopped.

It would be something nice to have. Not a big priority for the moment but when things calm down would be a cool feature :).

**Comment by aserdean** [comment]
Assigned to @svinturis

**Comment by svinturis** [comment]
I had a look at this issue and understood what is happening in case a driver uninstall is performed while the userspace processes are still running. The uninstall command will remove the OVS net component, "OvsExt". This means that the userspace processes will not be able to communicate with the ovs extension driver anymore, due to the fact that the PNP manager will not accept any userspace requests to the driver. The uninstall process will wait for the ovs driver to unload, but, because there are handles created by the ovs daemon and not closed, the ovs driver is not unloaded. That is why the reboot of the machine is requested and no subsequent driver installations are allowed.

The current uninstall method, i.e. using netcfg command from the script, does not allow any unload notification from userspace to be sent to the driver. So no subsequent actions can be taken from the kernel. 

So, the solution I propose is to close all ovs driver references from userspace and also close the ovs daemon, when no communication is possible with the ovs driver. In this way the ovs driver will be unloaded and the uninstall process will finish successfully without requiring a restart.

**Comment by aserdean** [comment]
Closed with commit: https://github.com/openvswitch/ovs/commit/d553dd54b33b255d042265a4563e66efc01480df
